config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :items
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations" }
  root 'home#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :picture, ImagesUploader

  validates :first_name, :last_name, :street_name, :street_number, :suburb,
            :state, :postcode, :country, presence: true

  def full_address
    [street_number, street_name, suburb, postcode, country].compact.join(',')
  end

  geocoded_by :full_address
  after_validation :geocode

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
    @hash = Gmaps4rails.build_markers(@profiles) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      marker.infowindow user.first_name
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :street_number, :street_name, :suburb, :state, :country, :postcode, :picture, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"><br>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field"><br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field"><br>
    <%= f.label :street_number %>
    <%= f.number_field :street_number %>
  </div>
  <div class="field"><br>
    <%= f.label :street_name %>
    <%= f.text_field :street_name %>
  </div>
  <div class="field"><br>
    <%= f.label :suburb %>
    <%= f.text_field :suburb %>
  </div>
  <div class="field"><br>
    <%= f.label :state %>
    <%= f.select(:state,['NSW', 'QLD', 'VIC', 'ACT', 'WA', 'SA', 'NT']) %>
  </div>
  <div class="field"><br>
    <%= f.label :country %>
    <%= f.select(:country,['Australia']) %>
  </div>
  <div class="field"><br>
    <%= f.label :postcode %>
    <%= f.number_field :postcode %>
  </div>
  <div class="field"><br>
    <%= f.label :picture %>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Street number</th>
      <th>Street name</th>
      <th>Suburb</th>
      <th>State</th>
      <th>Country</th>
      <th>Postcode</th>
      <th>Picture</th>
      <th>latitudes</th>
      <th>longitudes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.street_number %></td>
        <td><%= profile.street_name %></td>
        <td><%= profile.suburb %></td>
        <td><%= profile.state %></td>
        <td><%= profile.country %></td>
        <td><%= profile.postcode %></td>
        <td><%= image_tag(profile.picture_url(:thumbnail), :width => 50, :height => 50) %></td>
        <td><%= profile.latitude %></td>
        <td><%= profile.longitude %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

<!-- Show Profiles Location -->
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>


<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>Street number:</strong>
  <%= @profile.street_number %>
</p>

<p>
  <strong>Street name:</strong>
  <%= @profile.street_name %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @profile.suburb %>
</p>

<p>
  <strong>State:</strong>
  <%= @profile.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @profile.country %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @profile.postcode %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@profile.picture_url(:thumbnail), :width => 50, :height => 50) %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>


<!-- Show Profiles Location -->
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>


<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": <%= @profile.latitude %>,
        "lng": <%= @profile.longitude %>,
        "picture": {
          "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
          "width":  32,
          "height": 32
        },
        "infowindow": "hello!"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>