config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :items
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations" }
  root 'home#index'

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">BUYZAAR</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Buy", items_path, class: "buy" %></li>
          <li><%= link_to "Sell", new_item_path %></li>
          <% if current_user.has_role? :seller %>
            <li><%= link_to "Sales", orders_path %></li>
          <% else %>
            <li><%= link_to "Purchases", orders_path %> </li>
          <% end %>

          <li><%= link_to "Profile", profile_path(current_user.profile) if current_user.profile %> </li>
        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">

            <% if user_signed_in? %>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Log In", new_user_session_path %></li>
              <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>