config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :items
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations" }
  root 'home#index'

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :item
  # I am on the orders table, I am looking for my ouyer which is a User
  #I need to look at the buyer_id (which is a user) to find my buyer
  belongs_to :buyer, class_name: "User", foreign_key: "buyer_id"
  #I am on the orders table, I am looking for my seller which is a User
  # I need to look at the seller_id (which is a user) to find my seller
  belongs_to :seller, class_name: "User", foreign_key: "seller_id"
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    #Original code
    #@order = Order.new(order_params)

    # We need to make a new order that is associated with the current_user,
    # the seller and the item that you clicked on.
    @item = Item.find(order_params[:item_id])
    @order = current_user.purchases.build(seller: @item.user, item: @item)


    respond_to do |format|
      if @order.save
        format.html { redirect_to @item, notice: "You just purchased #{@item.name}" }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to orders_path, notice: 'Thanks for leaving feedback.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:feedback_comment, :feedback_rating, :buyer_id, :seller_id, :item_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.text_area :feedback_comment%>
    <%= f.input :feedback_rating %>
  </div>

  <div class="form-actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Leave Feedback</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Feedback comment</th>
      <th>Feedback rating</th>
      <th>Buyer</th>
      <th>Seller</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <!-- Add a condition to check if feedback is present with the method .present -->
        <% if order.feedback_comment.present? %>
          <td><%= order.feedback_comment %></td>
        <% else %>
          <td><%= link_to 'Leave Feedback', edit_order_path(order), class: "btn btn-primary" %></td>
        <% end %>
        <td><%= order.feedback_rating %></td>
        <td><%= order.buyer.profile.first_name %></td>
        <td><%= order.seller.profile.first_name %></td>
        <td><%= order.item.name%></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Feedback comment:</strong>
  <%= @order.feedback_comment %>
</p>

<p>
  <strong>Feedback rating:</strong>
  <%= @order.feedback_rating %>
</p>

<p>
  <strong>Buyer:</strong>
  <%= @order.buyer_id %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @order.seller_id %>
</p>

<p>
  <strong>Item:</strong>
  <%= @order.item_id %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>