config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :items
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations" }
  root 'home#index'

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one :order

    mount_uploader :image, ImagesUploader
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  # load_and_authorize_resource except: :create

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @order = Order.new
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user = current_user
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :image, :category, :description, :quantity, :rating, :user_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %><br>
    <%= f.input :price %><br>
    <%= f.input :image, as: :file%><br>
    <%= f.input :category, :label => 'Category', :collection => ['Retail', 'Tech', 'Vehicles'] %><br>
    <%= f.input :description %><br>
    <%= f.input :quantity %><br>
    <%= f.input :rating, :label => 'Rating', :collection => [1,2,3,4,5] %><br>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<div class="row">
  <% @items.each do |item| %>
  <div class="col-lg-4 col-md col-sm-2">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= link_to item_path(item) do %>
          <%= image_tag(item.image_url(:thumbnail), class: "img-responsive") %>
        <% end %>
        <h4> Name: <%= item.name %> </h4>
        <h5> Price: <%=item.price %> </h5>
      </div>
    </div>
  </div>
  <% end %>
</div>


<br>

<!-- <% if can? :manage, @item %> -->
 <%= link_to 'New Item', new_item_path %>
<!-- <% end %> -->

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image:</strong>
    <%= image_tag(@item.image_url(:thumbnail), :width => 50, :height => 50) %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @item.rating %>
</p>

<!-- We need a buy button -->
<%= simple_form_for(@order) do |f| %>
  <%= f.hidden_field :item_id, value: @item.id %>
  <div class="form-actions">
    <%= f.submit "Buy", class: "btn btn-info" %>
  </div>
<% end %>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>